### ISSUE TITLE
Does not scroll to section when click on menu item in the top bar

### ISSUE THREAD

**Issue by kimyvgy** [viblo-asia/machine-learning-landing-page#1]
Ex: If you're in plagiarism detection page, click on "Services" in the top bar, the page will redirect to the home page but the page does not scroll to "Services" section.

Now, if you click on "Services" again, the page will scroll to "Services" section.

This is a live page: https://machine-learning.viblo.asia

**Comment by tuananhp-1844** [comment]
i will grab this one

**Comment by kimnh-0823** [comment]
@tuananhp-1844 Go ahead  :)

**Comment by tuananhp-1844** [comment]
Bro check it for me. #5
