### ISSUE TITLE
Fix vulnerabilities security

### ISSUE THREAD

**Issue by kimnh-0823** [viblo-asia/machine-learning-landing-page#3]
As the title, we have 3 vulnerabilities in the dependencies. Please check the [network alerts](https://github.com/viblo-asia/machine-learning-landing-page/network/alerts) page. I have yet to be able to fix these vulnerabilities. Could you please help us!

There is a live page: https://machine-learning.viblo.asia

**Comment by ghost** [comment]
@kimnh-0823 the page shows 404. Please check once.

**Comment by kimnh-0823** [comment]
@sukhdeepg Hi, this page is private. Let fork the repository then you will see the same page in your fork-repository.

**Comment by kimyvgy** [comment]
@TroyTae it seems none vulnerabilities are fixed in Github security alerts. Let feel free to create another PR for it. Take your time!

**Comment by ghost** [comment]
@kimnh-0823 
Oh really?
How can I see it?
![image](https://user-images.githubusercontent.com/20078201/66039242-4556bc00-e54f-11e9-8652-c2a9dff2fff2.png)
Here is my Security Alerts in the forked repository.

**Comment by kimyvgy** [comment]
@TroyTae Let me check this issue again! Maybe the vulnerabilities are fixed. I wonder Github is detecting issues on `yarn.lock` file which is not changed in your PR. Therefore, security alerts are still there. Maybe? :thinking:

**Comment by ghost** [comment]
@kimnh-0823 
Ah I see!
I didn't commit the `yarn.lock`, because `yarn.lock` is changed that depends on the version of yarn.
Can you update `yarn.lock` and check again please?

**Comment by kimyvgy** [comment]
@TroyTae That's right! I updated! The issue is solved. Thank you so much for your PR!
